settings:
    import/resolver:
        webpack:
           config: examples/webpack.config.js
rules:
    import/no-extraneous-dependencies: off
    import/no-relative-parent-imports: off
    no-magic-numbers: off
